only enter top level root symbols when reading the class/tasty file.
scalacenter/tasty-query pull request #77
Opened 2022-09-01 16:28 UTC by bishabosha

differences:
- getDecl will now force a
  top level class' inner definitions,
  this is not observable from the public API,
  but some LazyLoadingSuite tests needed to
  change.
- getTopLevelTasty now accepts any top level
  class or module symbol.

add test case, assert no class for standalone object

experiment: replace `objclass"foo"` with `tname"foo" / obj`

2022-09-05 14:50 UTC, sjrd requested changes
Nice :) I only have minor comments.

2022-09-06 14:59 UTC, adpi2 commented on jvm/src/test/scala/tastyquery/TypeSuite.scala
> +    scalaRuntime.declarations
Added this failing test to show that the reading of Java signatures is too eager.

2022-09-06 14:59 UTC, adpi2 commented on jvm/src/test/scala/tastyquery/TypeSuite.scala
> +    scalaRuntime.declarations
I also added the rt.jar in the `JavaTestPlatform` to run this test, but only when running in Java 8, which is why this test is not yet compatible with other Java versions.

To read Java 9+ class files, one could use something like this:
https://github.com/scalacenter/scala-debug-adapter/blob/0a25d3424bf5acfb4dcbebeada8fae980f4dc4bb/core/src/main/scala/ch/epfl/scala/debugadapter/ClassSystem.scala#L28-L36

2022-09-07 07:49 UTC, adpi2 commented on jvm/src/test/scala/tastyquery/TypeSuite.scala
> +    scalaRuntime.declarations
The problem is described in https://github.com/scalacenter/tasty-query/issues/80 and it should probably fixed in another PR.

2022-09-08 15:07 UTC, merged